export {
  CreativeIcon,
  FitnessIcon,
  TechnologyIcon,
  CookingIcon,
  EducationIcon,
  YogaIcon,
  HIITIcon,
  CardioIcon,
  GroupTrainingIcon,
  EsportsIcon,
  PilatesIcon,
  StrengthTrainingIcon,
  DanceIcon,
  BoxingIcon,
  StretchingIcon,
  MeditationIcon,
  OtherIcon,
} from './CategoryIcons';

